namespace Smart.Data.Accessor.Builders.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using SourceGenerateHelper;

[Generator]
public sealed class EntityBuilderGenerator : IIncrementalGenerator
{
    private const string Ns = "Smart.Data.Accessor.Builders.";
    private const string DataAccessorAttributeName = "Smart.Data.Accessor.Attributes.DataAccessorAttribute";
    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";
    private const string AutoGeneratedAttributeName = "Smart.Data.Accessor.Attributes.AutoGeneratedAttribute";
    private const string KeyAttributeName = "Smart.Data.Accessor.Attributes.KeyAttribute";
    private const string BuilderContextFullName = "Smart.Data.Accessor.Builders.BuilderContext";

    private static readonly (string Attribute, BuilderKind Kind)[] Targets =
    [
        (Ns + "SelectBuilderAttribute", BuilderKind.Select),
        (Ns + "SelectSingleBuilderAttribute", BuilderKind.SelectSingle),
        (Ns + "UpdateBuilderAttribute", BuilderKind.Update),
        (Ns + "DeleteBuilderAttribute", BuilderKind.Delete),
        (Ns + "CountBuilderAttribute", BuilderKind.Count),
        (Ns + "TruncateBuilderAttribute", BuilderKind.Truncate),
    ];

    private enum BuilderKind
    {
        Select,
        SelectSingle,
        Update,
        Delete,
        Count,
        Truncate,
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = Targets.Select(t =>
        {
            var kind = t.Kind;
            return context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    t.Attribute,
                    static (s, _) => s is MethodDeclarationSyntax,
                    (ctx, _) => (ctx, kind))
                .Collect();
        }).ToArray();

        var combined = providers[0];
        for (var i = 1; i < providers.Length; i++)
        {
            var local = providers[i];
            combined = combined.Combine(local).Select((pair, _) => pair.Left.AddRange(pair.Right));
        }

        context.RegisterSourceOutput(combined, static (spc, src) => Execute(spc, src));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<(GeneratorAttributeSyntaxContext Ctx, BuilderKind Kind)> entries)
    {
        var groups = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)>>(SymbolEqualityComparer.Default);

        foreach (var (ctx, kind) in entries)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method || ctx.TargetNode is not MethodDeclarationSyntax syntax)
            {
                continue;
            }
            if (!method.IsPartialDefinition)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidMethod, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            var container = method.ContainingType;
            if (syntax.Parent is not ClassDeclarationSyntax containerSyntax || !containerSyntax.Modifiers.Any(t => t.Text == "partial"))
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidContainer, syntax.Identifier.GetLocation(), container.Name));
                continue;
            }

            var attrName = Targets.First(t => t.Kind == kind).Attribute;
            var attr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == attrName);
            if (attr is null)
            {
                continue;
            }

            if (method.Parameters.Length < 1 ||
                method.Parameters[0].Type.ToDisplayString() != BuilderContextFullName ||
                method.Parameters[0].RefKind != RefKind.Ref)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidSignature, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            if (kind == BuilderKind.Update && method.Parameters.Length < 2)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.BuilderRequiresEntityParameter, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            if (!groups.TryGetValue(container, out var list))
            {
                list = [];
                groups[container] = list;
            }
            list.Add((method, attr, syntax, kind));
        }

        foreach (var kv in groups)
        {
            var source = Emit(context, kv.Key, kv.Value);
            var ns = kv.Key.ContainingNamespace.IsGlobalNamespace
                ? "global"
                : kv.Key.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var filename = $"{ns}_{kv.Key.Name}.EntityBuilders.g.cs";
            context.AddSource(filename, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string Emit(SourceProductionContext context, INamedTypeSymbol container, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)> entries)
    {
        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        var dialect = ResolveDialect(container);
        var typeMaps = MappingResolver.ReadTypeMaps(container);

        builder.Indent().Append(AccessibilityText(container.DeclaredAccessibility)).Append(" partial class ").Append(container.Name).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var (method, attr, syntax, kind) in entries)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            EmitMethod(context, builder, container, method, attr, syntax, kind, dialect, typeMaps);
        }

        builder.EndScope();
        return builder.ToString();
    }

    private static void EmitMethod(
        SourceProductionContext context,
        SourceBuilder builder,
        INamedTypeSymbol container,
        IMethodSymbol method,
        AttributeData attr,
        MethodDeclarationSyntax syntax,
        BuilderKind kind,
        DialectInfo dialect,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var entityType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;
        var tableName = entityType.Name;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                tableName = s;
            }
        }

        var props = ReadEntityColumns(entityType);

        var ctxParamName = method.Parameters[0].Name;
        var methodAccess = AccessibilityText(method.DeclaredAccessibility);
        var staticPrefix = method.IsStatic ? "static " : string.Empty;

        var paramText = new StringBuilder();
        paramText.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ");
        paramText.Append(ctxParamName);
        for (var i = 1; i < method.Parameters.Length; i++)
        {
            var p = method.Parameters[i];
            paramText.Append(", ");
            paramText.Append(p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            paramText.Append(' ');
            paramText.Append(p.Name);
        }

        builder.Indent().Append(methodAccess).Append(" ").Append(staticPrefix).Append("partial void ")
            .Append(method.Name).Append("(").Append(paramText.ToString()).Append(")").NewLine();
        builder.BeginScope();

        builder.Indent().Append("var cmd = ").Append(ctxParamName).Append(".Command;").NewLine();

        switch (kind)
        {
            case BuilderKind.Update:
                EmitUpdate(context, builder, container, method, syntax, entityType, tableName, props, dialect, typeMaps);
                break;
            case BuilderKind.Delete:
                EmitDelete(context, builder, method, syntax, entityType, tableName, props, dialect, typeMaps);
                break;
            case BuilderKind.Count:
                EmitCount(builder, tableName, dialect);
                break;
            case BuilderKind.Truncate:
                EmitTruncate(builder, tableName, dialect);
                break;
            case BuilderKind.Select:
                EmitSelect(builder, tableName, props, dialect);
                break;
            case BuilderKind.SelectSingle:
                EmitSelectSingle(context, builder, method, syntax, entityType, tableName, props, dialect, typeMaps);
                break;
        }

        builder.EndScope();
    }

    private static void EmitUpdate(
        SourceProductionContext context,
        SourceBuilder builder,
        INamedTypeSymbol container,
        IMethodSymbol method,
        MethodDeclarationSyntax syntax,
        INamedTypeSymbol entityType,
        string tableName,
        List<EntityColumn> props,
        DialectInfo dialect,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var entityParamName = method.Parameters[1].Name;
        var settable = props.Where(p => !p.IsKey && !p.IsAutoGenerated).ToList();
        var keys = props.Where(p => p.IsKey).ToList();

        if (keys.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.NoKeyForBuilder,
                syntax.Identifier.GetLocation(),
                entityType.Name,
                method.Name));
        }

        var sqlBuilder = new StringBuilder();
        sqlBuilder.Append("UPDATE ").Append(dialect.Quote(tableName)).Append(" SET ");
        for (var i = 0; i < settable.Count; i++)
        {
            if (i > 0)
            {
                sqlBuilder.Append(", ");
            }
            sqlBuilder.Append(dialect.Quote(settable[i].Column)).Append(" = ").Append(dialect.Marker).Append(settable[i].PropertyName);
        }
        if (keys.Count > 0)
        {
            sqlBuilder.Append(" WHERE ");
            for (var i = 0; i < keys.Count; i++)
            {
                if (i > 0)
                {
                    sqlBuilder.Append(" AND ");
                }
                sqlBuilder.Append(dialect.Quote(keys[i].Column)).Append(" = ").Append(dialect.Marker).Append("k_").Append(keys[i].PropertyName);
            }
        }

        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sqlBuilder.ToString())).Append(";").NewLine();

        var reportLocation = syntax.Identifier.GetLocation();
        foreach (var p in settable)
        {
            var pName = dialect.Marker + p.PropertyName;
            ParameterEmitter.EmitEntityPropertyParameter(
                builder,
                pName,
                $"{entityParamName}.{p.PropertyName}",
                p.Symbol,
                typeMaps,
                container,
                context,
                reportLocation);
        }
        foreach (var p in keys)
        {
            var pName = dialect.Marker + "k_" + p.PropertyName;
            ParameterEmitter.EmitEntityPropertyParameter(
                builder,
                pName,
                $"{entityParamName}.{p.PropertyName}",
                p.Symbol,
                typeMaps,
                container,
                context,
                reportLocation);
        }
    }

    private static void EmitDelete(
        SourceProductionContext context,
        SourceBuilder builder,
        IMethodSymbol method,
        MethodDeclarationSyntax syntax,
        INamedTypeSymbol entityType,
        string tableName,
        List<EntityColumn> props,
        DialectInfo dialect,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var keys = props.Where(p => p.IsKey).ToList();
        if (keys.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.NoKeyForBuilder,
                syntax.Identifier.GetLocation(),
                entityType.Name,
                method.Name));
        }

        var sqlBuilder = new StringBuilder();
        sqlBuilder.Append("DELETE FROM ").Append(dialect.Quote(tableName));
        var ki = 0;
        var extraParams = method.Parameters.Length - 1;
        if (keys.Count > 0 && extraParams > 0)
        {
            sqlBuilder.Append(" WHERE ");
            for (var i = 1; i < method.Parameters.Length && ki < keys.Count; i++, ki++)
            {
                if (ki > 0)
                {
                    sqlBuilder.Append(" AND ");
                }
                var paramName = method.Parameters[i].Name;
                sqlBuilder.Append(dialect.Quote(keys[ki].Column)).Append(" = ").Append(dialect.Marker).Append(paramName);
            }
        }

        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sqlBuilder.ToString())).Append(";").NewLine();

        ki = 0;
        for (var i = 1; i < method.Parameters.Length && ki < keys.Count; i++, ki++)
        {
            var paramName = method.Parameters[i].Name;
            var markerName = dialect.Marker + paramName;
            ParameterEmitter.EmitMethodParameterBinding(
                builder,
                markerName,
                paramName,
                method.Parameters[i].Type,
                typeMaps);
        }
    }

    private static void EmitCount(SourceBuilder builder, string tableName, DialectInfo dialect)
    {
        var sql = "SELECT COUNT(*) FROM " + dialect.Quote(tableName);
        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sql)).Append(";").NewLine();
    }

    private static void EmitTruncate(SourceBuilder builder, string tableName, DialectInfo dialect)
    {
        // Sqlite has no TRUNCATE TABLE — use DELETE FROM (spec §8.1 / Sprint F #40c).
        var sql = dialect.IsSqlite
            ? "DELETE FROM " + dialect.Quote(tableName)
            : "TRUNCATE TABLE " + dialect.Quote(tableName);
        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sql)).Append(";").NewLine();
    }

    private static void EmitSelect(SourceBuilder builder, string tableName, List<EntityColumn> props, DialectInfo dialect)
    {
        // Sprint 5.3 will refine column projection. Sprint 5.2 emits the full column list (excluding [Ignore])
        // so Example.ConsoleApplication.SelectAll remains operational across the phase boundary.
        var cols = string.Join(", ", props.Select(p => dialect.Quote(p.Column)));
        var sql = "SELECT " + cols + " FROM " + dialect.Quote(tableName);
        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sql)).Append(";").NewLine();
    }

    private static void EmitSelectSingle(
        SourceProductionContext context,
        SourceBuilder builder,
        IMethodSymbol method,
        MethodDeclarationSyntax syntax,
        INamedTypeSymbol entityType,
        string tableName,
        List<EntityColumn> props,
        DialectInfo dialect,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var keys = props.Where(p => p.IsKey).ToList();
        if (keys.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.NoKeyForBuilder,
                syntax.Identifier.GetLocation(),
                entityType.Name,
                method.Name));
        }

        var sqlBuilder = new StringBuilder();
        sqlBuilder.Append("SELECT ");
        for (var i = 0; i < props.Count; i++)
        {
            if (i > 0)
            {
                sqlBuilder.Append(", ");
            }
            sqlBuilder.Append(dialect.Quote(props[i].Column));
        }
        sqlBuilder.Append(" FROM ").Append(dialect.Quote(tableName));

        var ki = 0;
        if (keys.Count > 0 && method.Parameters.Length > 1)
        {
            sqlBuilder.Append(" WHERE ");
            for (var i = 1; i < method.Parameters.Length && ki < keys.Count; i++, ki++)
            {
                if (ki > 0)
                {
                    sqlBuilder.Append(" AND ");
                }
                sqlBuilder.Append(dialect.Quote(keys[ki].Column)).Append(" = ").Append(dialect.Marker).Append(method.Parameters[i].Name);
            }
        }

        builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sqlBuilder.ToString())).Append(";").NewLine();

        ki = 0;
        for (var i = 1; i < method.Parameters.Length && ki < keys.Count; i++, ki++)
        {
            var paramName = method.Parameters[i].Name;
            var markerName = dialect.Marker + paramName;
            ParameterEmitter.EmitMethodParameterBinding(
                builder,
                markerName,
                paramName,
                method.Parameters[i].Type,
                typeMaps);
        }
    }

    private static List<EntityColumn> ReadEntityColumns(INamedTypeSymbol entityType)
    {
        var list = new List<EntityColumn>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            var isKey = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KeyAttributeName);
            var isAuto = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AutoGeneratedAttributeName);
            list.Add(new EntityColumn(column, p.Name, isKey, isAuto, p));
        }
        return list;
    }

    private static DialectInfo ResolveDialect(INamedTypeSymbol container)
    {
        var attr = container.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DataAccessorAttributeName);
        var dialectType = attr?.NamedArguments
            .FirstOrDefault(kv => kv.Key == "Dialect").Value.Value as INamedTypeSymbol;
        var fq = dialectType?.ToDisplayString() ?? "Smart.Data.Accessor.Dialect.AnsiDialect";
        return fq switch
        {
            "Smart.Data.Accessor.Dialect.SqlServerDialect" => new DialectInfo("[", "]", "@", isSqlite: false),
            "Smart.Data.Accessor.Dialect.MySqlDialect" => new DialectInfo("`", "`", "@", isSqlite: false),
            "Smart.Data.Accessor.Dialect.SqliteDialect" => new DialectInfo("\"", "\"", "@", isSqlite: true),
            _ => new DialectInfo("\"", "\"", "@", isSqlite: false),
        };
    }

    private static string EncodeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string AccessibilityText(Accessibility a) => a switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal",
    };

    private readonly record struct EntityColumn(string Column, string PropertyName, bool IsKey, bool IsAutoGenerated, IPropertySymbol Symbol);

    private readonly struct DialectInfo
    {
        public string OpenQuote { get; }
        public string CloseQuote { get; }
        public string Marker { get; }
        public bool IsSqlite { get; }

        public DialectInfo(string openQuote, string closeQuote, string marker, bool isSqlite)
        {
            OpenQuote = openQuote;
            CloseQuote = closeQuote;
            Marker = marker;
            IsSqlite = isSqlite;
        }

        public string Quote(string name) => OpenQuote + name + CloseQuote;
    }
}
