namespace Smart.Data.Accessor.Builders.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Source generator for the remaining entity-based builders introduced in Phase 2 §3.4:
/// SelectBuilder / SelectSingleBuilder / UpdateBuilder / DeleteBuilder / CountBuilder / TruncateBuilder.
/// </summary>
[Generator]
public sealed class EntityBuilderGenerator : IIncrementalGenerator
{
    private const string Ns = "Smart.Data.Accessor.Builders.";

    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";
    private const string AutoGeneratedAttributeName = "Smart.Data.Accessor.Attributes.AutoGeneratedAttribute";
    private const string KeyAttributeName = "Smart.Data.Accessor.Attributes.KeyAttribute";

    private static readonly (string Attribute, BuilderKind Kind)[] Targets =
    [
        (Ns + "SelectBuilderAttribute", BuilderKind.Select),
        (Ns + "SelectSingleBuilderAttribute", BuilderKind.SelectSingle),
        (Ns + "UpdateBuilderAttribute", BuilderKind.Update),
        (Ns + "DeleteBuilderAttribute", BuilderKind.Delete),
        (Ns + "CountBuilderAttribute", BuilderKind.Count),
        (Ns + "TruncateBuilderAttribute", BuilderKind.Truncate),
    ];

    private enum BuilderKind
    {
        Select,
        SelectSingle,
        Update,
        Delete,
        Count,
        Truncate,
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = Targets.Select(t =>
        {
            var kind = t.Kind;
            return context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    t.Attribute,
                    static (s, _) => s is MethodDeclarationSyntax,
                    (ctx, _) => (ctx, kind))
                .Collect();
        }).ToArray();

        // Combine all into one source output.
        var combined = providers[0];
        for (var i = 1; i < providers.Length; i++)
        {
            var local = providers[i];
            combined = combined.Combine(local).Select((pair, _) => pair.Left.AddRange(pair.Right));
        }

        context.RegisterSourceOutput(combined, static (spc, src) => Execute(spc, src));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<(GeneratorAttributeSyntaxContext Ctx, BuilderKind Kind)> entries)
    {
        var groups = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)>>(SymbolEqualityComparer.Default);

        foreach (var (ctx, kind) in entries)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method || ctx.TargetNode is not MethodDeclarationSyntax syntax)
            {
                continue;
            }
            if (!method.IsPartialDefinition)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidMethod, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            var container = method.ContainingType;
            if (syntax.Parent is not ClassDeclarationSyntax containerSyntax || !containerSyntax.Modifiers.Any(t => t.Text == "partial"))
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidContainer, syntax.Identifier.GetLocation(), container.Name));
                continue;
            }

            var attrName = Targets.First(t => t.Kind == kind).Attribute;
            var attr = method.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == attrName);
            if (attr is null)
            {
                continue;
            }

            if (method.Parameters.Length < 1 ||
                method.Parameters[0].Type.ToDisplayString() != "Smart.Data.Accessor.Builders.BuilderContext" ||
                method.Parameters[0].RefKind != RefKind.Ref)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidSignature, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            if (!groups.TryGetValue(container, out var list))
            {
                list = [];
                groups[container] = list;
            }
            list.Add((method, attr, syntax, kind));
        }

        foreach (var kv in groups)
        {
            var source = Emit(kv.Key, kv.Value);
            var ns = kv.Key.ContainingNamespace.IsGlobalNamespace
                ? "global"
                : kv.Key.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var filename = $"{ns}_{kv.Key.Name}.EntityBuilders.g.cs";
            context.AddSource(filename, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string Emit(INamedTypeSymbol container, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"{AccText(container.DeclaredAccessibility)} partial class {container.Name}");
        sb.AppendLine("{");

        var first = true;
        foreach (var (method, attr, _, kind) in entries)
        {
            if (!first)
            {
                sb.AppendLine();
            }
            first = false;
            EmitMethod(sb, method, attr, kind);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, IMethodSymbol method, AttributeData attr, BuilderKind kind)
    {
        var entityType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;
        var tableName = entityType.Name;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                tableName = s;
            }
        }

        var entityFq = entityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var props = new List<(string Column, string PropName, bool IsKey, bool IsAutoGenerated)>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            var isKey = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KeyAttributeName);
            var isAuto = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AutoGeneratedAttributeName);
            props.Add((column, p.Name, isKey, isAuto));
        }

        var methodAccess = AccText(method.DeclaredAccessibility);
        var staticPrefix = method.IsStatic ? "static " : string.Empty;

        // Signature
        var paramText = new StringBuilder();
        paramText.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ctx");
        for (var i = 1; i < method.Parameters.Length; i++)
        {
            var p = method.Parameters[i];
            paramText.Append(", ");
            paramText.Append(p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            paramText.Append(' ');
            paramText.Append(p.Name);
        }

        sb.AppendLine($"    {methodAccess} {staticPrefix}partial void {method.Name}({paramText})");
        sb.AppendLine("    {");

        switch (kind)
        {
            case BuilderKind.Select:
            case BuilderKind.SelectSingle:
                EmitSelect(sb, tableName, props, kind == BuilderKind.SelectSingle, method);
                break;
            case BuilderKind.Update:
                EmitUpdate(sb, tableName, props, method);
                break;
            case BuilderKind.Delete:
                EmitDelete(sb, tableName, props, method);
                break;
            case BuilderKind.Count:
                EmitCount(sb, tableName);
                break;
            case BuilderKind.Truncate:
                EmitTruncate(sb, tableName);
                break;
        }

        sb.AppendLine("    }");
    }

    private static void EmitSelect(StringBuilder sb, string table, List<(string Column, string PropName, bool IsKey, bool IsAutoGenerated)> props, bool single, IMethodSymbol method)
    {
        var cols = string.Join(", ", props.Select(p => p.Column));
        sb.AppendLine($"        ctx.Sql.Append(\"SELECT {cols} FROM {table}\");");
        if (single)
        {
            var keys = props.Where(p => p.IsKey).ToList();
            if (keys.Count == 0)
            {
                // Fallback: all extra params become WHERE (best effort).
                keys = props.Take(1).ToList();
            }
            EmitWhereFromParameters(sb, keys, method, startParamIndex: 1);
        }
    }

    private static void EmitUpdate(StringBuilder sb, string table, List<(string Column, string PropName, bool IsKey, bool IsAutoGenerated)> props, IMethodSymbol method)
    {
        // Convention: first non-ctx parameter is the entity.
        if (method.Parameters.Length < 2)
        {
            sb.AppendLine("        // UpdateBuilder requires an entity parameter.");
            return;
        }
        var entityParam = method.Parameters[1].Name;

        var settable = props.Where(p => !p.IsKey && !p.IsAutoGenerated).ToList();
        var keys = props.Where(p => p.IsKey).ToList();
        if (keys.Count == 0)
        {
            sb.AppendLine("        // UpdateBuilder: no [Key] property found — emitting no WHERE clause.");
        }

        sb.AppendLine($"        ctx.Sql.Append(\"UPDATE {table} SET \");");
        var firstSet = true;
        foreach (var (col, name, _, _) in settable)
        {
            if (!firstSet)
            {
                sb.AppendLine("        ctx.Sql.Append(\", \");");
            }
            firstSet = false;
            sb.AppendLine($"        ctx.Sql.Append(\"{col} = @{name}\");");
            sb.AppendLine($"        ctx.AddInParameter(\"@{name}\", {entityParam}.{name});");
        }
        if (keys.Count > 0)
        {
            sb.AppendLine("        ctx.Sql.Append(\" WHERE \");");
            var firstKey = true;
            foreach (var (col, name, _, _) in keys)
            {
                if (!firstKey)
                {
                    sb.AppendLine("        ctx.Sql.Append(\" AND \");");
                }
                firstKey = false;
                sb.AppendLine($"        ctx.Sql.Append(\"{col} = @k_{name}\");");
                sb.AppendLine($"        ctx.AddInParameter(\"@k_{name}\", {entityParam}.{name});");
            }
        }
    }

    private static void EmitDelete(StringBuilder sb, string table, List<(string Column, string PropName, bool IsKey, bool IsAutoGenerated)> props, IMethodSymbol method)
    {
        sb.AppendLine($"        ctx.Sql.Append(\"DELETE FROM {table}\");");
        var keys = props.Where(p => p.IsKey).ToList();
        EmitWhereFromParameters(sb, keys, method, startParamIndex: 1);
    }

    private static void EmitCount(StringBuilder sb, string table)
    {
        sb.AppendLine($"        ctx.Sql.Append(\"SELECT COUNT(*) FROM {table}\");");
    }

    private static void EmitTruncate(StringBuilder sb, string table)
    {
        sb.AppendLine($"        ctx.Sql.Append(\"TRUNCATE TABLE {table}\");");
    }

    private static void EmitWhereFromParameters(StringBuilder sb, List<(string Column, string PropName, bool IsKey, bool IsAutoGenerated)> keys, IMethodSymbol method, int startParamIndex)
    {
        if (keys.Count == 0 || method.Parameters.Length <= startParamIndex)
        {
            return;
        }

        sb.AppendLine("        ctx.Sql.Append(\" WHERE \");");
        var firstKey = true;
        var ki = 0;
        for (var i = startParamIndex; i < method.Parameters.Length && ki < keys.Count; i++, ki++)
        {
            var p = method.Parameters[i];
            var (col, _, _, _) = keys[ki];
            if (!firstKey)
            {
                sb.AppendLine("        ctx.Sql.Append(\" AND \");");
            }
            firstKey = false;
            sb.AppendLine($"        ctx.Sql.Append(\"{col} = @{p.Name}\");");
            sb.AppendLine($"        ctx.AddInParameter(\"@{p.Name}\", {p.Name});");
        }
    }

    private static string AccText(Accessibility a) => a switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal",
    };
}
