namespace Smart.Data.Accessor.Builders.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class InsertBuilderGenerator : IIncrementalGenerator
{
    private const string InsertBuilderAttributeName = "Smart.Data.Accessor.Builders.InsertBuilderAttribute";
    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                InsertBuilderAttributeName,
                static (s, _) => s is MethodDeclarationSyntax,
                static (ctx, _) => ctx)
            .Collect();

        context.RegisterSourceOutput(methods, static (spc, src) => Execute(spc, src));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<GeneratorAttributeSyntaxContext> methods)
    {
        var groups = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax)>>(SymbolEqualityComparer.Default);

        foreach (var ctx in methods)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method || ctx.TargetNode is not MethodDeclarationSyntax syntax)
            {
                continue;
            }

            if (!method.IsPartialDefinition)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidMethod, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            var container = method.ContainingType;
            if (syntax.Parent is not ClassDeclarationSyntax containerSyntax || !containerSyntax.Modifiers.Any(t => t.Text == "partial"))
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidContainer, syntax.Identifier.GetLocation(), container.Name));
                continue;
            }

            var attr = method.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == InsertBuilderAttributeName);

            if (method.Parameters.Length != 2 ||
                method.Parameters[0].Type.ToDisplayString() != "Smart.Data.Accessor.Builders.BuilderContext")
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidSignature, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            if (!groups.TryGetValue(container, out var list))
            {
                list = [];
                groups[container] = list;
            }
            list.Add((method, attr, syntax));
        }

        foreach (var kv in groups)
        {
            var source = Emit(kv.Key, kv.Value);
            var ns = kv.Key.ContainingNamespace.IsGlobalNamespace
                ? "global"
                : kv.Key.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var filename = $"{ns}_{kv.Key.Name}.Builders.g.cs";
            context.AddSource(filename, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string Emit(INamedTypeSymbol container, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"{Accessibility(container.DeclaredAccessibility)} partial class {container.Name}");
        sb.AppendLine("{");

        var first = true;
        foreach (var (method, attr, _) in entries)
        {
            if (!first)
            {
                sb.AppendLine();
            }
            first = false;
            EmitBuilderMethod(sb, method, attr);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBuilderMethod(StringBuilder sb, IMethodSymbol method, AttributeData attr)
    {
        var entityType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;
        var tableName = entityType.Name;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                tableName = s;
            }
        }

        var entityParamName = method.Parameters[1].Name;
        var entityFq = entityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var columns = new List<(string Column, string Prop)>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Microsoft.CodeAnalysis.Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            columns.Add((column, p.Name));
        }

        var methodAccess = Accessibility(method.DeclaredAccessibility);
        var staticPrefix = method.IsStatic ? "static " : string.Empty;

        sb.AppendLine($"    {methodAccess} {staticPrefix}partial void {method.Name}(global::Smart.Data.Accessor.Builders.BuilderContext ctx, {entityFq} {entityParamName})");
        sb.AppendLine("    {");
        var colList = string.Join(", ", columns.Select(c => c.Column));
        var paramList = string.Join(", ", columns.Select(c => "@" + c.Prop));
        sb.AppendLine($"        ctx.Sql.Append(\"INSERT INTO {tableName} ({colList}) VALUES ({paramList})\");");
        foreach (var (_, prop) in columns)
        {
            sb.AppendLine($"        ctx.AddParameter(\"@{prop}\", {entityParamName}.{prop});");
        }
        sb.AppendLine("    }");
    }

    private static string Accessibility(Accessibility a) => a switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal",
    };
}
