namespace Smart.Data.Accessor.Builders.Generator;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class InsertBuilderGenerator : IIncrementalGenerator
{
    private const string InsertBuilderAttributeName = "Smart.Data.Accessor.Builders.InsertBuilderAttribute";
    private const string DataAccessorAttributeName = "Smart.Data.Accessor.Attributes.DataAccessorAttribute";
    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";
    private const string AutoGeneratedAttributeName = "Smart.Data.Accessor.Attributes.AutoGeneratedAttribute";
    private const string BuilderContextFullName = "Smart.Data.Accessor.Builders.BuilderContext";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                InsertBuilderAttributeName,
                static (s, _) => s is MethodDeclarationSyntax,
                static (ctx, _) => ctx)
            .Collect();

        context.RegisterSourceOutput(methods, static (spc, src) => Execute(spc, src));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<GeneratorAttributeSyntaxContext> methods)
    {
        var groups = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax)>>(SymbolEqualityComparer.Default);

        foreach (var ctx in methods)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method || ctx.TargetNode is not MethodDeclarationSyntax syntax)
            {
                continue;
            }

            if (!method.IsPartialDefinition)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidMethod, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            var container = method.ContainingType;
            if (syntax.Parent is not ClassDeclarationSyntax containerSyntax || !containerSyntax.Modifiers.Any(t => t.Text == "partial"))
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidContainer, syntax.Identifier.GetLocation(), container.Name));
                continue;
            }

            var attr = method.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == InsertBuilderAttributeName);

            if (method.Parameters.Length < 2 ||
                method.Parameters[0].Type.ToDisplayString() != BuilderContextFullName ||
                method.Parameters[0].RefKind != RefKind.Ref)
            {
                context.ReportDiagnostic(Diagnostic.Create(Diagnostics.InvalidSignature, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            if (!groups.TryGetValue(container, out var list))
            {
                list = [];
                groups[container] = list;
            }
            list.Add((method, attr, syntax));
        }

        foreach (var kv in groups)
        {
            var source = Emit(context, kv.Key, kv.Value);
            var ns = kv.Key.ContainingNamespace.IsGlobalNamespace
                ? "global"
                : kv.Key.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var filename = $"{ns}_{kv.Key.Name}.Builders.g.cs";
            context.AddSource(filename, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string Emit(SourceProductionContext context, INamedTypeSymbol container, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        var dialect = ResolveDialect(container);
        var typeMaps = MappingResolver.ReadTypeMaps(container);

        sb.AppendLine($"{AccessibilityText(container.DeclaredAccessibility)} partial class {container.Name}");
        sb.AppendLine("{");

        var first = true;
        foreach (var (method, attr, syntax) in entries)
        {
            if (!first)
            {
                sb.AppendLine();
            }
            first = false;
            EmitBuilderMethod(context, sb, container, method, attr, syntax, dialect, typeMaps);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBuilderMethod(
        SourceProductionContext context,
        StringBuilder sb,
        INamedTypeSymbol container,
        IMethodSymbol method,
        AttributeData attr,
        MethodDeclarationSyntax syntax,
        DialectInfo dialect,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var entityType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;
        var tableName = entityType.Name;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                tableName = s;
            }
        }

        var ctxParamName = method.Parameters[0].Name;
        var entityParamName = method.Parameters[1].Name;

        var columns = new List<(string Column, string Prop, IPropertySymbol Symbol)>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Microsoft.CodeAnalysis.Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AutoGeneratedAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            columns.Add((column, p.Name, p));
        }

        var methodAccess = AccessibilityText(method.DeclaredAccessibility);
        var staticPrefix = method.IsStatic ? "static " : string.Empty;

        var paramText = new StringBuilder();
        paramText.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ");
        paramText.Append(ctxParamName);
        for (var i = 1; i < method.Parameters.Length; i++)
        {
            var p = method.Parameters[i];
            paramText.Append(", ");
            paramText.Append(p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            paramText.Append(' ');
            paramText.Append(p.Name);
        }

        sb.AppendLine($"    {methodAccess} {staticPrefix}partial void {method.Name}({paramText})");
        sb.AppendLine("    {");

        var quotedTable = dialect.Quote(tableName);
        var colSql = string.Join(", ", columns.Select(c => dialect.Quote(c.Column)));
        var valSql = string.Join(", ", columns.Select(c => dialect.Marker + c.Prop));
        var sqlText = $"INSERT INTO {quotedTable} ({colSql}) VALUES ({valSql})";

        sb.AppendLine($"        var cmd = {ctxParamName}.Command;");
        sb.AppendLine($"        cmd.CommandText = {EncodeStringLiteral(sqlText)};");
        foreach (var (_, prop, sym) in columns)
        {
            var pName = dialect.Marker + prop;
            ParameterEmitter.EmitEntityPropertyParameter(
                sb,
                pName,
                $"{entityParamName}.{prop}",
                sym,
                typeMaps,
                container,
                context,
                syntax.Identifier.GetLocation());
        }

        sb.AppendLine("    }");
    }

    private static DialectInfo ResolveDialect(INamedTypeSymbol container)
    {
        var attr = container.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DataAccessorAttributeName);
        var dialectType = attr?.NamedArguments
            .FirstOrDefault(kv => kv.Key == "Dialect").Value.Value as INamedTypeSymbol;
        var fq = dialectType?.ToDisplayString() ?? "Smart.Data.Accessor.Dialect.AnsiDialect";
        return fq switch
        {
            "Smart.Data.Accessor.Dialect.SqlServerDialect" => new DialectInfo("[", "]", "@"),
            "Smart.Data.Accessor.Dialect.MySqlDialect" => new DialectInfo("`", "`", "@"),
            _ => new DialectInfo("\"", "\"", "@"),
        };
    }

    private readonly struct DialectInfo
    {
        public string OpenQuote { get; }
        public string CloseQuote { get; }
        public string Marker { get; }

        public DialectInfo(string openQuote, string closeQuote, string marker)
        {
            OpenQuote = openQuote;
            CloseQuote = closeQuote;
            Marker = marker;
        }

        public string Quote(string name) => OpenQuote + name + CloseQuote;
    }

    private static string EncodeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string AccessibilityText(Accessibility a) => a switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal",
        Microsoft.CodeAnalysis.Accessibility.Private => "private",
        Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
        Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
        Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal",
    };
}
