namespace Smart.Data.Accessor.Attributes;

using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Marks a property as auto-generated by the database (identity, default, sequence, etc.).
/// Excluded from INSERT/UPDATE Builder column lists but still mapped in query results.
/// </summary>
/// <remarks>
/// Phase 2 §2.3: re-introduced so that <see cref="IgnoreAttribute"/> can keep its
/// original "ignore everywhere" semantics.
/// </remarks>
[AttributeUsage(AttributeTargets.Property)]
[ExcludeFromCodeCoverage]
public sealed class AutoGeneratedAttribute : Attribute
{
}
