namespace Smart.Data.Accessor.Builders.Generator.Builders;

using System.Collections.Generic;
using System.Linq;
using System.Threading;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using Smart.Data.Accessor.Builders.Generator.Engine;
using Smart.Data.Accessor.Builders.Generator.Models;
using Smart.Data.Accessor.CodeGen;

using SourceGenerateHelper;

/// <summary>
/// spec §7.11 (P4): the FAWMN transform for the Builder generators. Reads the [DataAccessor] class
/// symbol fully and returns an equatable <see cref="BuilderClassModel"/> (no symbols leak past this
/// boundary), so <see cref="QueryBuilderEngine"/>'s output stage stays incremental. All attribute
/// reading, entity-column enumeration and converter/DbType/enum resolution happen here.
/// Shared source (linked into each builder generator assembly).
/// </summary>
internal static class BuilderModelBuilder
{
    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";
    private const string AutoGeneratedAttributeName = "Smart.Data.Accessor.Attributes.AutoGeneratedAttribute";
    private const string KeyAttributeName = "Smart.Data.Accessor.Attributes.KeyAttribute";
    private const string CancellationTokenTypeName = "System.Threading.CancellationToken";
    private const string LimitAttributeName = "Smart.Data.Accessor.Builders.LimitAttribute";
    private const string OffsetAttributeName = "Smart.Data.Accessor.Builders.OffsetAttribute";

    public static BuilderClassModel Build(
        GeneratorAttributeSyntaxContext ctx,
        IReadOnlyList<(string Attribute, QueryBuilderEngine.BuilderKind Kind)> targets,
        CancellationToken ct)
    {
        var container = (INamedTypeSymbol)ctx.TargetSymbol;
        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        var accessibility = GenExpr.AccessibilityText(container.DeclaredAccessibility);
        var isPartial = ctx.TargetNode is ClassDeclarationSyntax classSyntax && classSyntax.Modifiers.Any(static t => t.Text == "partial");

        var typeMaps = MappingResolver.ReadTypeMaps(container);
        var profile = MappingResolver.ResolveProfile(container);

        var diagnostics = new List<BuilderDiagnosticData>();
        var methods = new List<BuilderMethodModel>();

        foreach (var member in container.GetMembers())
        {
            ct.ThrowIfCancellationRequested();
            if (member is not IMethodSymbol method)
            {
                continue;
            }

            var matched = new List<(AttributeData Attr, QueryBuilderEngine.BuilderKind Kind)>();
            foreach (var attrData in method.GetAttributes())
            {
                var fq = attrData.AttributeClass?.ToDisplayString();
                foreach (var target in targets)
                {
                    if (target.Attribute == fq)
                    {
                        matched.Add((attrData, target.Kind));
                        break;
                    }
                }
            }

            if (matched.Count == 0)
            {
                continue;
            }

            var location = method.Locations.FirstOrDefault();

            // SDB0002: the container is not a partial class, so the helper cannot be emitted.
            if (!isPartial)
            {
                diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.InvalidContainer, location, container.Name));
                continue;
            }

            // SDB0006: more than one of this generator's QueryBuilder attributes on the same method.
            if (matched.Count > 1)
            {
                diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.QueryBuilderDuplicated, location, method.Name));
                continue;
            }

            var model = BuildMethod(container, method, matched[0].Attr, matched[0].Kind, typeMaps, profile, diagnostics);
            if (model is not null)
            {
                methods.Add(model);
            }
        }

        return new BuilderClassModel(
            ns,
            container.Name,
            accessibility,
            new EquatableArray<BuilderMethodModel>(methods.ToArray()),
            new EquatableArray<BuilderDiagnosticData>(diagnostics.ToArray()));
    }

    private static BuilderMethodModel? BuildMethod(
        INamedTypeSymbol container,
        IMethodSymbol method,
        AttributeData attr,
        QueryBuilderEngine.BuilderKind kind,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        INamedTypeSymbol? profile,
        List<BuilderDiagnosticData> diagnostics)
    {
        var location = method.Locations.FirstOrDefault();

        var entityType = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;
        string? table = null;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                table = s;
            }
        }

        var tableName = table ?? entityType?.Name;
        if (tableName is null)
        {
            // SDB0004: neither an entity type nor a Table name was supplied.
            diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.MissingTable, location, method.Name));
            return null;
        }

        // design doc §4.3: value parameters = method params excluding DbConnection / DbTransaction / CancellationToken.
        var valueParamSymbols = method.Parameters
            .Where(p => !IsCancellationToken(p.Type) && !IsDbConnection(p.Type) && !IsDbTransaction(p.Type))
            .ToList();
        var valueParams = valueParamSymbols.Select(p => ResolveValueParam(p, typeMaps)).ToArray();

        // The entity instance is the first non-paging value parameter whose type matches EntityType.
        var entityParam = entityType is null
            ? null
            : valueParamSymbols.FirstOrDefault(p =>
                !HasAttribute(p, LimitAttributeName) &&
                !HasAttribute(p, OffsetAttributeName) &&
                SymbolEqualityComparer.Default.Equals(p.Type, entityType));
        var hasEntityType = entityType is not null;

        var entityColumns = entityType is null
            ? Enumerable.Empty<EntityColumn>()
            : ReadEntityColumns(entityType);
        var columns = entityColumns
            .Select(c => ResolveColumn(c, method, container, profile, typeMaps, diagnostics, location))
            .ToArray();

        var valueParamsEq = new EquatableArray<BuilderValueParam>(valueParams);
        var columnsEq = new EquatableArray<BuilderColumn>(columns);

        switch (kind)
        {
            case QueryBuilderEngine.BuilderKind.Insert:
                return new InsertModel(method.Name, tableName, valueParamsEq, columnsEq, entityParam?.Name);

            case QueryBuilderEngine.BuilderKind.Update:
                if (!hasEntityType || entityParam is null)
                {
                    // SDB0005: cannot resolve the column list (no entity instance).
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, method.Name));
                }
                else if (!columns.Any(static c => c.IsKey))
                {
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType!.Name, method.Name));
                }
                return new UpdateModel(method.Name, tableName, valueParamsEq, columnsEq, entityParam?.Name, hasEntityType);

            case QueryBuilderEngine.BuilderKind.Delete:
                if (hasEntityType && !columns.Any(static c => c.IsKey))
                {
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType!.Name, method.Name));
                }
                return new DeleteModel(method.Name, tableName, valueParamsEq, columnsEq, hasEntityType);

            case QueryBuilderEngine.BuilderKind.Count:
                return new CountModel(method.Name, tableName, valueParamsEq);

            case QueryBuilderEngine.BuilderKind.Truncate:
                return new TruncateModel(method.Name, tableName, valueParamsEq);

            case QueryBuilderEngine.BuilderKind.Select:
                if (!hasEntityType)
                {
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, method.Name));
                }
                return new SelectModel(method.Name, tableName, valueParamsEq, columnsEq, hasEntityType);

            case QueryBuilderEngine.BuilderKind.SelectSingle:
                if (!hasEntityType)
                {
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, method.Name));
                }
                else if (!columns.Any(static c => c.IsKey))
                {
                    diagnostics.Add(BuilderDiagnosticData.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType!.Name, method.Name));
                }
                return new SelectSingleModel(method.Name, tableName, valueParamsEq, columnsEq, hasEntityType);

            default:
                return null;
        }
    }

    // spec §7.4 / §7.7 / §7.9: resolve a method value parameter's binding metadata (DbType / enum; no
    // converter — matching the existing behaviour). The value expression at output is the parameter name.
    private static BuilderValueParam ResolveValueParam(IParameterSymbol p, Dictionary<ITypeSymbol, TypeMapInfo> typeMaps)
    {
        var typeFq = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hasEnum = TryGetEnumUnderlying(p.Type, out var enumUnderlying, out var isNullableEnum);

        string? dbTypeExpr = null;
        int? size = null;
        if (MappingResolver.TryGetTypeMap(p.Type, typeMaps, out var info))
        {
            dbTypeExpr = info.DbTypeExpr;
            size = info.Size;
        }

        return new BuilderValueParam(
            p.Name,
            typeFq,
            ColumnName(p),
            HasAttribute(p, LimitAttributeName),
            HasAttribute(p, OffsetAttributeName),
            hasEnum ? enumUnderlying : null,
            isNullableEnum,
            dbTypeExpr,
            size);
    }

    // spec §7.4 / §7.7 / §7.9: resolve an entity column's binding metadata (converter / DbType / enum /
    // nullability). The value expression at output is "<entityParam>.<PropertyName>".
    private static BuilderColumn ResolveColumn(
        EntityColumn c,
        IMethodSymbol method,
        INamedTypeSymbol container,
        INamedTypeSymbol? profile,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        List<BuilderDiagnosticData> diagnostics,
        Location? location)
    {
        var prop = c.Symbol;
        var handler = MappingResolver.ResolveTypeHandler(prop, method, container, profile);
        var explicitDbType = MappingResolver.ResolvePropertyDbType(prop);

        // SDA0148: a [TypeHandler] wins over a [TypeMap] for the same type; warn the [TypeMap] is dead.
        if (handler is not null && MappingResolver.HasTypeMapFor(prop.Type, typeMaps))
        {
            diagnostics.Add(BuilderDiagnosticData.Create(
                BuilderDiagnostics.TypeMapTypeHandlerConflict,
                location,
                container.Name,
                prop.Type.ToDisplayString(),
                prop.Name));
        }

        // spec §7.7 (P8): when a valid converter applies, capture TConverter + its IValueConverter<TDb,TClr>
        // type args so the value binds via ExecuteHelper.AddInParameter<TConverter,TDb,TClr> (ToDb + null
        // handling centralised in the helper — no gen-time value expression / nullability flags needed).
        BuilderConverterBinding? converter = null;
        if (handler is not null && ScopeResolver.TryGetConverterTypes(handler, out var convDb, out var convClr))
        {
            converter = new BuilderConverterBinding(
                handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                convDb.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                convClr.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        // p.DbType: an explicit property-scope [DbType] wins; otherwise a [TypeMap] default applies only
        // when no converter rewrites the value (a converter governs the DB type).
        string? dbTypeExpr = null;
        int? size = null;
        if (explicitDbType is not null)
        {
            dbTypeExpr = explicitDbType;
        }
        else if (converter is null && MappingResolver.TryGetTypeMap(prop.Type, typeMaps, out var info))
        {
            dbTypeExpr = info.DbTypeExpr;
            size = info.Size;
        }

        var hasEnum = TryGetEnumUnderlying(prop.Type, out var enumUnderlying, out var isNullableEnum);

        return new BuilderColumn(
            c.Column,
            c.PropertyName,
            c.IsKey,
            c.IsAutoGenerated,
            converter,
            hasEnum ? enumUnderlying : null,
            isNullableEnum,
            dbTypeExpr,
            size);
    }

    private static List<EntityColumn> ReadEntityColumns(INamedTypeSymbol entityType)
    {
        var list = new List<EntityColumn>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            var isKey = p.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == KeyAttributeName);
            var isAuto = p.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == AutoGeneratedAttributeName);
            list.Add(new EntityColumn(column, p.Name, isKey, isAuto, p));
        }
        return list;
    }

    private static string ColumnName(IParameterSymbol p)
        => p.GetAttributes()
            .FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
            ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;

    private static bool HasAttribute(IParameterSymbol p, string attributeName)
        => p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attributeName);

    private static bool IsCancellationToken(ITypeSymbol type) => type.ToDisplayString() == CancellationTokenTypeName;

    private static bool IsDbConnection(ITypeSymbol type) => InheritsFrom(type, "System.Data.Common.DbConnection");

    private static bool IsDbTransaction(ITypeSymbol type) => InheritsFrom(type, "System.Data.Common.DbTransaction");

    private static bool InheritsFrom(ITypeSymbol type, string baseFullName)
    {
        for (var current = type as INamedTypeSymbol; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == baseFullName)
            {
                return true;
            }
        }
        return false;
    }

    private static bool TryGetEnumUnderlying(ITypeSymbol propertyType, out string underlyingFullyQualified, out bool isNullable)
    {
        underlyingFullyQualified = string.Empty;
        isNullable = false;

        INamedTypeSymbol? enumSym = null;
        if (propertyType is INamedTypeSymbol nt && nt.IsGenericType &&
            nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T &&
            nt.TypeArguments[0] is INamedTypeSymbol inner && inner.TypeKind == TypeKind.Enum)
        {
            enumSym = inner;
            isNullable = true;
        }
        else if (propertyType is INamedTypeSymbol named && named.TypeKind == TypeKind.Enum)
        {
            enumSym = named;
        }

        if (enumSym?.EnumUnderlyingType is null)
        {
            return false;
        }

        underlyingFullyQualified = enumSym.EnumUnderlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return true;
    }

    private readonly record struct EntityColumn(string Column, string PropertyName, bool IsKey, bool IsAutoGenerated, IPropertySymbol Symbol);
}
