namespace Smart.Data.Accessor.Generator.Tests;

using Microsoft.CodeAnalysis;

using Smart.Data.Accessor.Builders.Generator;
using Smart.Data.Accessor.Builders.Generator.Engine;
using Smart.Data.Accessor.Builders.Generator.Models;

using SourceGenerateHelper;

using Xunit;

// BuilderSourceBuilder.Build is a pure (BuilderClassModel, SqlDialect) -> string function, so the emitted
// QueryBuilder helper can be unit-tested from a hand-built model without a generator driver — the
// testability win of the 3-layer split (spec §7.11.4). ProviderBuilderTests exercise the full pipeline.
public sealed class BuilderSourceBuilderTests
{
    private static BuilderColumn Col(string name, bool isKey = false, bool isAutoGenerated = false) =>
        new(name, name, isKey, isAutoGenerated, null, null, false, null, null);

    private static BuilderClassModel Model(BuilderMethodModel method) =>
        new(
            "Test.Generated",
            "SampleAccessor",
            Accessibility.Public,
            new EquatableArray<BuilderMethodModel>([method]),
            new EquatableArray<DiagnosticInfo>([]));

    [Fact]
    public void InsertEmitsPartialClassQueryBuilderAndStatement()
    {
        var insert = new InsertModel(
            "Insert",
            "Users",
            new EquatableArray<BuilderValueParam>([
                new BuilderValueParam("entity", "global::Test.User", "entity", false, false, null, false, null, null)
            ]),
            new EquatableArray<BuilderColumn>([Col("Id", isKey: true), Col("Name")]),
            "entity");

        var source = BuilderSourceBuilder.Build(Model(insert), new AnsiSqlDialect());

        Assert.Contains("public partial class SampleAccessor", source, StringComparison.Ordinal);
        Assert.Contains("private static void Insert__QueryBuilder(", source, StringComparison.Ordinal);
        // AnsiSqlDialect double-quotes identifiers; StringLiteral escapes the quotes in the C# literal.
        Assert.Contains("INSERT INTO \\\"Users\\\" (\\\"Id\\\", \\\"Name\\\") VALUES (@Id, @Name)", source, StringComparison.Ordinal);
        Assert.Contains("AddInParameter(cmd, \"@Id\", entity.Id", source, StringComparison.Ordinal);
        Assert.Contains("AddInParameter(cmd, \"@Name\", entity.Name", source, StringComparison.Ordinal);
    }

    [Fact]
    public void CountEmitsCountStatement()
    {
        var count = new CountModel(
            "Count",
            "Users",
            new EquatableArray<BuilderValueParam>([]));

        var source = BuilderSourceBuilder.Build(Model(count), new AnsiSqlDialect());

        Assert.Contains("private static void Count__QueryBuilder(", source, StringComparison.Ordinal);
        Assert.Contains("SELECT COUNT(*) FROM \\\"Users\\\"", source, StringComparison.Ordinal);
    }
}
