<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Smart.Data.Accessor.Generator.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <NoWarn>$(NoWarn);CS1685</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="SourceGenerateHelper" Version="1.25.0" />
    <PackageReference Include="SourceGenerateHelper.Testing" Version="1.25.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Smart.Data.Accessor.Generator\Smart.Data.Accessor.Generator.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.SqlServer.Generator\Smart.Data.Accessor.Builders.SqlServer.Generator.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.MySql.Generator\Smart.Data.Accessor.Builders.MySql.Generator.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.Postgres.Generator\Smart.Data.Accessor.Builders.Postgres.Generator.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor\Smart.Data.Accessor.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.SqlServer\Smart.Data.Accessor.Builders.SqlServer.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.MySql\Smart.Data.Accessor.Builders.MySql.csproj" />
    <ProjectReference Include="..\Smart.Data.Accessor.Builders.Postgres\Smart.Data.Accessor.Builders.Postgres.csproj" />
  </ItemGroup>

</Project>
