namespace Smart.Data.Accessor.Builders.Generator.Models;

// v1 skeleton (spec.md §7.11.1). Filled in by Phase 5.x.
internal sealed record BuilderColumnModel(
    string PropertyName,
    string ColumnName,
    string ClrTypeFullName,
    bool IsKey,
    bool IsAutoGenerated,
    bool IsIgnoredOnUpdate,
    string? DbTypeExpr);
