namespace Smart.Data.Accessor.Builders.Generator.Models;

// spec §7.11 (P4): an entity column resolved in the FAWMN transform (symbol stage). Carries the
// column/property names + key/auto flags AND the fully-resolved parameter-binding metadata
// (converter / DbType / enum / nullability) so the output stage can emit the binding without symbols.
internal sealed record BuilderColumn(
    string ColumnName,
    string PropertyName,
    bool IsKey,
    bool IsAutoGenerated,
    // spec §7.4 / §7.7: converter FQN when a [TypeHandler<>] applies (value written via TConverter.ToDb); null otherwise.
    string? ConverterTypeFullName,
    // property type is Nullable<T> (checked first in the converter value-expression: HasValue branch).
    bool IsNullableValueType,
    bool IsValueType,
    // spec §7.9: underlying primitive FQN when the property type is an enum (or Nullable<enum>); null otherwise.
    string? EnumUnderlyingFullName,
    bool IsNullableEnum,
    // final p.DbType expression to emit: explicit [DbType] wins, else a [TypeMap] default when no converter applies; null when none.
    string? DbTypeExpr,
    int? Size);
