namespace Smart.Data.Accessor.Shared.Builders;

using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using SourceGenerateHelper;

// 各 provider の QueryBuilder 出力が共有する出力段：診断を報告し、メソッドがあれば partial クラスを足場として組み、各メソッドを
// provider の emitMethod で出力して AddSource する。メソッド本体（kind 分岐＋SQL 組み立て）は各 provider が供給する。Model 型に依存しない。
// Output stage shared by the providers' QueryBuilder generators: report diagnostics and, when there is at least one method,
// scaffold the partial class, emit each method via the provider's emitMethod callback, and AddSource. The per-method body
// (kind dispatch + SQL assembly) is supplied by each provider. Independent of the model type.
internal static class SourceOutput
{
    public static void Emit<TMethod>(
        SourceProductionContext context,
        string ns,
        string className,
        Accessibility accessibility,
        EquatableArray<TMethod> methods,
        EquatableArray<DiagnosticInfo> diagnostics,
        Action<SourceBuilder, TMethod> emitMethod,
        string providerTag)
    {
        foreach (var diagnostic in diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (methods.Count == 0)
        {
            return;
        }

        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        if (!String.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        builder.Indent().Append(accessibility.ToText()).Append(" partial class ").Append(className).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var method in methods)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            emitMethod(builder, method);
        }

        builder.EndScope();

        var nsForFile = String.IsNullOrEmpty(ns) ? "global" : ns.Replace('.', '_');
        var filename = $"{nsForFile}_{className}.QueryBuilders{providerTag}.g.cs";
        context.AddSource(filename, SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
