namespace Smart.Data.Accessor.Generator.Models;

// v1 skeleton (spec.md §7.11.1). Filled in by Phase 6.3.
internal sealed record ColumnModel(
    string PropertyName,
    string ColumnName,
    string ClrTypeFullName,
    bool IsNullable,
    bool IsKey,
    bool IsIgnored,
    bool IsAutoGenerated,
    EnumUnderlyingKind? EnumKind,
    string? DbTypeExpr,
    int? Size,
    ConverterBindingModel? Converter);

internal enum EnumUnderlyingKind
{
    SByte,
    Byte,
    Int16,
    UInt16,
    Int32,
    UInt32,
    Int64,
    UInt64
}
