namespace Smart.Data.Accessor.Builders.Generator.Engine;

using System.Text;

using Smart.Data.Accessor.Builders.Generator.Models;
using Smart.Data.Accessor.GeneratorShared;

using SourceGenerateHelper;

// spec §7.11.4: emit stage for the QueryBuilder generators (Model -> generated C# string; symbol-free
// so it is unit-testable from a hand-built BuilderClassModel). Driven by QueryBuilderEngine's output
// stage. The only per-provider variation is identifier quoting + the paging clause (via SqlDialect).
internal static class BuilderSourceBuilder
{
    private const string QueryBuilderMethodSuffix = "__QueryBuilder";
    private const char Marker = '@';

    internal static string Build(BuilderClassModel model, SqlDialect dialect)
    {
        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        builder.Indent().Append(model.Accessibility.ToText()).Append(" partial class ").Append(model.ClassName).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var method in model.Methods)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            EmitMethod(builder, method, dialect);
        }

        builder.EndScope();
        return builder.ToString();
    }

    private static void EmitMethod(SourceBuilder builder, BuilderMethodModel method, SqlDialect dialect)
    {
        // Signature: private static void {Method}__QueryBuilder(ref BuilderContext ctx, <value params>)
        var sig = new StringBuilder();
        sig.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ctx");
        foreach (var p in method.ValueParams)
        {
            sig.Append(", ").Append(p.TypeFullName).Append(' ').Append(p.Name);
        }

        builder.Indent().Append("private static void ").Append(method.MethodName).Append(QueryBuilderMethodSuffix)
            .Append("(").Append(sig.ToString()).Append(")").NewLine();
        builder.BeginScope();
        builder.Indent().Append("var cmd = ctx.Command;").NewLine();

        switch (method)
        {
            case InsertModel m:
                EmitInsert(builder, m, dialect);
                break;
            case UpdateModel m:
                EmitUpdate(builder, m, dialect);
                break;
            case DeleteModel m:
                EmitDelete(builder, m, dialect);
                break;
            case CountModel m:
                EmitCommandText(builder, "SELECT COUNT(*) FROM " + dialect.Quote(m.TableName));
                break;
            case TruncateModel m:
                EmitCommandText(builder, "TRUNCATE TABLE " + dialect.Quote(m.TableName));
                break;
            case SelectModel m:
                EmitSelect(builder, m, dialect);
                break;
            case SelectSingleModel m:
                EmitSelectSingle(builder, m, dialect);
                break;
        }

        builder.EndScope();
    }

    private static void EmitInsert(SourceBuilder builder, InsertModel m, SqlDialect dialect)
    {
        if (m.EntityParamName is not null)
        {
            // Entity mode: columns from entity properties (excluding [AutoGenerated]).
            var cols = m.Columns.Where(static c => !c.IsAutoGenerated).ToList();
            var colSql = String.Join(", ", cols.Select(c => dialect.Quote(c.ColumnName)));
            var valSql = String.Join(", ", cols.Select(c => Marker + c.PropertyName));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(m.TableName)} ({colSql}) VALUES ({valSql})");
            foreach (var c in cols)
            {
                EmitColumnParameter(builder, Marker + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
            }
        }
        else
        {
            // Parameter mode: columns / values from the bind parameters.
            var bindParams = BindParams(m);
            var colSql = String.Join(", ", bindParams.Select(p => dialect.Quote(p.ColumnName)));
            var valSql = String.Join(", ", bindParams.Select(p => Marker + p.Name));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(m.TableName)} ({colSql}) VALUES ({valSql})");
            foreach (var p in bindParams)
            {
                EmitValueParamBinding(builder, p);
            }
        }
    }

    private static void EmitUpdate(SourceBuilder builder, UpdateModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType || (m.EntityParamName is null))
        {
            EmitCommandText(builder, "UPDATE " + dialect.Quote(m.TableName) + " SET ");
            return;
        }

        var columns = m.Columns;
        var settable = columns.Where(static c => !c.IsKey && !c.IsAutoGenerated).ToList();
        var keys = columns.Where(static c => c.IsKey).ToList();

        var sql = new StringBuilder();
        sql.Append("UPDATE ").Append(dialect.Quote(m.TableName)).Append(" SET ");
        for (var i = 0; i < settable.Count; i++)
        {
            if (i > 0)
            {
                sql.Append(", ");
            }
            sql.Append(dialect.Quote(settable[i].ColumnName)).Append(" = ").Append(Marker).Append(settable[i].PropertyName);
        }
        if (keys.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < keys.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                sql.Append(dialect.Quote(keys[i].ColumnName)).Append(" = ").Append(Marker).Append("k_").Append(keys[i].PropertyName);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var c in settable)
        {
            EmitColumnParameter(builder, Marker + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
        }
        foreach (var c in keys)
        {
            EmitColumnParameter(builder, Marker + "k_" + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
        }
    }

    private static void EmitDelete(SourceBuilder builder, DeleteModel m, SqlDialect dialect)
    {
        var keyColumns = m.Columns.Where(static c => c.IsKey).ToList();
        var bindParams = BindParams(m);

        var sql = new StringBuilder();
        sql.Append("DELETE FROM ").Append(dialect.Quote(m.TableName));
        if (bindParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < bindParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = i < keyColumns.Count ? keyColumns[i].ColumnName : bindParams[i].ColumnName;
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(bindParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in bindParams)
        {
            EmitValueParamBinding(builder, p);
        }
    }

    private static void EmitSelect(SourceBuilder builder, SelectModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType)
        {
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(m.TableName));
            return;
        }

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(String.Join(", ", m.Columns.Select(c => dialect.Quote(c.ColumnName)))).Append(" FROM ").Append(dialect.Quote(m.TableName));

        // Phase 7: append the provider paging clause when [Limit]/[Offset] params are present.
        var valueParams = m.ValueParams;
        var limitParam = valueParams.FirstOrDefault(static p => p.IsLimit);
        var offsetParam = valueParams.FirstOrDefault(static p => p.IsOffset);
        if ((limitParam is not null) || (offsetParam is not null))
        {
            dialect.AppendPaging(
                sql,
                limitParam is null ? null : Marker + limitParam.Name,
                offsetParam is null ? null : Marker + offsetParam.Name);
        }

        EmitCommandText(builder, sql.ToString());

        if (offsetParam is not null)
        {
            EmitValueParamBinding(builder, offsetParam);
        }
        if (limitParam is not null)
        {
            EmitValueParamBinding(builder, limitParam);
        }
    }

    private static void EmitSelectSingle(SourceBuilder builder, SelectSingleModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType)
        {
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(m.TableName));
            return;
        }

        var keyColumns = m.Columns.Where(static c => c.IsKey).ToList();
        var bindParams = BindParams(m);

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(String.Join(", ", m.Columns.Select(c => dialect.Quote(c.ColumnName)))).Append(" FROM ").Append(dialect.Quote(m.TableName));
        if (bindParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < bindParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = i < keyColumns.Count ? keyColumns[i].ColumnName : bindParams[i].ColumnName;
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(bindParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in bindParams)
        {
            EmitValueParamBinding(builder, p);
        }
    }

    // Bind parameters = value parameters minus the [Limit]/[Offset] paging parameters.
    private static List<BuilderValueParam> BindParams(BuilderMethodModel m)
        => m.ValueParams.Where(static p => !p.IsLimit && !p.IsOffset).ToList();

    // Entity column parameter, bound via ExecuteHelper.AddInParameter (P7 / spec §7.11: L1 plumbing
    // centralised). DbType / Size are passed as call arguments (the helper sets p.DbType / p.Size /
    // p.Value / Direction). A [TypeHandler<>] column (P8) binds through the converter-sharing overload
    // AddInParameter<TConverter, TDb, TClr> — the value is passed raw and the helper calls ToDb + handles
    // null/DBNull; enum / plain columns pass the underlying-cast / plain value argument.
    private static void EmitColumnParameter(SourceBuilder builder, string paramName, string valueExpression, BuilderColumn c)
    {
        if (c.Converter is { } conv)
        {
            builder.Indent()
                .Append("global::Smart.Data.Accessor.Helpers.ExecuteHelper.")
                .Append(CodeExpressionHelper.AddInParameterConverter(conv.ConverterTypeFullName, conv.DbTypeFullName, conv.ClrTypeFullName))
                .Append("(cmd, \"")
                .Append(paramName).Append("\", ")
                .Append(valueExpression)
                .Append(CodeExpressionHelper.DbTypeSizeArgs(c.DbTypeExpr, c.Size))
                .Append(");").NewLine();
            return;
        }

        builder.Indent()
            .Append("global::Smart.Data.Accessor.Helpers.ExecuteHelper.AddInParameter(cmd, \"")
            .Append(paramName).Append("\", ")
            .Append(ColumnValueArg(valueExpression, c))
            .Append(CodeExpressionHelper.DbTypeSizeArgs(c.DbTypeExpr, c.Size))
            .Append(");").NewLine();
    }

    private static string ColumnValueArg(string valueExpr, BuilderColumn c)
        => c.EnumUnderlyingFullName is not null
            ? CodeExpressionHelper.EnumCastValue(c.EnumUnderlyingFullName, c.IsNullableEnum, valueExpr)
            : valueExpr;

    // Method value parameter (no converter — matching the prior behaviour): enum underlying cast or
    // plain value, bound via ExecuteHelper.AddInParameter.
    private static void EmitValueParamBinding(SourceBuilder builder, BuilderValueParam p)
        => builder.Indent()
            .Append("global::Smart.Data.Accessor.Helpers.ExecuteHelper.AddInParameter(cmd, \"")
            .Append(Marker).Append(p.Name).Append("\", ")
            .Append(ValueParamArg(p))
            .Append(CodeExpressionHelper.DbTypeSizeArgs(p.DbTypeExpr, p.Size))
            .Append(");").NewLine();

    private static string ValueParamArg(BuilderValueParam p)
        => p.EnumUnderlyingFullName is not null
            ? CodeExpressionHelper.EnumCastValue(p.EnumUnderlyingFullName, p.IsNullableEnum, p.Name)
            : p.Name;

    private static void EmitCommandText(SourceBuilder builder, string sql)
        => builder.Indent().Append("cmd.CommandText = ").Append(CodeExpressionHelper.StringLiteral(sql)).Append(";").NewLine();
}
