namespace Smart.Data.Accessor.Builders.Generator.Engine;

using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Smart.Data.Accessor.Builders.Generator.Models;

using SourceGenerateHelper;

// Output stage shared by the QueryBuilder generators in this assembly: report diagnostics, and (when there is at least
// one method) scaffold the partial class, emit each method via the provider's emitMethod callback, and AddSource. The
// per-method body (kind dispatch + SQL assembly) is supplied by each provider.
internal static class BuilderOutput
{
    public static void Emit(
        SourceProductionContext context,
        BuilderClassModel model,
        Action<SourceBuilder, BuilderMethodModel> emitMethod,
        string providerTag)
    {
        foreach (var diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.Methods.Count == 0)
        {
            return;
        }

        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        builder.Indent().Append(model.Accessibility.ToText()).Append(" partial class ").Append(model.ClassName).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var method in model.Methods)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            emitMethod(builder, method);
        }

        builder.EndScope();

        var nsForFile = String.IsNullOrEmpty(model.Namespace) ? "global" : model.Namespace.Replace('.', '_');
        var filename = $"{nsForFile}_{model.ClassName}.QueryBuilders{providerTag}.g.cs";
        context.AddSource(filename, SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
