namespace Smart.Data.Accessor.Builders.Generator.Engine;

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Smart.Data.Accessor.Builders.Generator.Builders;
using Smart.Data.Accessor.Builders.Generator.Models;

using SourceGenerateHelper;

/// <summary>
/// Dialect-parameterized QueryBuilder emit engine. Each provider's <c>[Generator]</c> calls
/// <see cref="Register"/> with its QueryBuilder attribute set + <see cref="SqlDialect"/>; registration
/// is on <c>[DataAccessor]</c> (spec §7.11, P4) so a single transform sees every attribute on a method.
/// The transform (<see cref="BuilderModelBuilder"/>) produces an equatable <see cref="BuilderClassModel"/>;
/// this engine's output stage emits the <c>{Method}__QueryBuilder</c> helpers purely from that model
/// (no symbols), keeping generation incremental. Shared source (linked into each builder generator
/// assembly); the only per-provider variation is identifier quoting + the paging clause.
/// </summary>
internal static class QueryBuilderEngine
{
    private const string DataAccessorAttributeName = "Smart.Data.Accessor.Attributes.DataAccessorAttribute";
    private const string QueryBuilderMethodSuffix = "__QueryBuilder";
    private const char Marker = '@';

    public enum BuilderKind
    {
        Insert,
        Update,
        Delete,
        Count,
        Select,
        SelectSingle,
        Truncate,
    }

    // spec §7.11 (P4): register a builder generator on [DataAccessor]. targets/dialect/providerTag are
    // generator-fixed values passed via closures (never part of the cached model).
    public static void Register(
        IncrementalGeneratorInitializationContext context,
        IReadOnlyList<(string Attribute, BuilderKind Kind)> targets,
        SqlDialect dialect,
        string providerTag)
    {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DataAccessorAttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                (ctx, ct) => BuilderModelBuilder.Build(ctx, targets, ct))
            .WithTrackingName("BuilderClassModel");

        context.RegisterSourceOutput(models, (spc, model) => Emit(spc, model, dialect, providerTag));
    }

    private static void Emit(SourceProductionContext context, BuilderClassModel model, SqlDialect dialect, string providerTag)
    {
        foreach (var diagnostic in model.Diagnostics.AsArray())
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        var methods = model.Methods.AsArray();
        if (methods.Length == 0)
        {
            return;
        }

        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        builder.Indent().Append(model.Accessibility).Append(" partial class ").Append(model.ClassName).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var method in methods)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            EmitMethod(builder, method, dialect);
        }

        builder.EndScope();

        var nsForFile = string.IsNullOrEmpty(model.Namespace) ? "global" : model.Namespace.Replace('.', '_');
        var filename = $"{nsForFile}_{model.ClassName}.QueryBuilders{providerTag}.g.cs";
        context.AddSource(filename, SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void EmitMethod(SourceBuilder builder, BuilderMethodModel method, SqlDialect dialect)
    {
        // Signature: private static void {Method}__QueryBuilder(ref BuilderContext ctx, <value params>)
        var sig = new StringBuilder();
        sig.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ctx");
        foreach (var p in method.ValueParams.AsArray())
        {
            sig.Append(", ").Append(p.TypeFullName).Append(' ').Append(p.Name);
        }

        builder.Indent().Append("private static void ").Append(method.MethodName).Append(QueryBuilderMethodSuffix)
            .Append("(").Append(sig.ToString()).Append(")").NewLine();
        builder.BeginScope();
        builder.Indent().Append("var cmd = ctx.Command;").NewLine();

        switch (method)
        {
            case InsertModel m:
                EmitInsert(builder, m, dialect);
                break;
            case UpdateModel m:
                EmitUpdate(builder, m, dialect);
                break;
            case DeleteModel m:
                EmitDelete(builder, m, dialect);
                break;
            case CountModel m:
                EmitCommandText(builder, "SELECT COUNT(*) FROM " + dialect.Quote(m.TableName));
                break;
            case TruncateModel m:
                EmitCommandText(builder, "TRUNCATE TABLE " + dialect.Quote(m.TableName));
                break;
            case SelectModel m:
                EmitSelect(builder, m, dialect);
                break;
            case SelectSingleModel m:
                EmitSelectSingle(builder, m, dialect);
                break;
        }

        builder.EndScope();
    }

    private static void EmitInsert(SourceBuilder builder, InsertModel m, SqlDialect dialect)
    {
        if (m.EntityParamName is not null)
        {
            // Entity mode: columns from entity properties (excluding [AutoGenerated]).
            var cols = m.Columns.AsArray().Where(static c => !c.IsAutoGenerated).ToList();
            var colSql = string.Join(", ", cols.Select(c => dialect.Quote(c.ColumnName)));
            var valSql = string.Join(", ", cols.Select(c => Marker + c.PropertyName));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(m.TableName)} ({colSql}) VALUES ({valSql})");
            foreach (var c in cols)
            {
                EmitColumnParameter(builder, Marker + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
            }
        }
        else
        {
            // Parameter mode: columns / values from the bind parameters.
            var bindParams = BindParams(m);
            var colSql = string.Join(", ", bindParams.Select(p => dialect.Quote(p.ColumnName)));
            var valSql = string.Join(", ", bindParams.Select(p => Marker + p.Name));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(m.TableName)} ({colSql}) VALUES ({valSql})");
            foreach (var p in bindParams)
            {
                EmitValueParamBinding(builder, p);
            }
        }
    }

    private static void EmitUpdate(SourceBuilder builder, UpdateModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType || m.EntityParamName is null)
        {
            EmitCommandText(builder, "UPDATE " + dialect.Quote(m.TableName) + " SET ");
            return;
        }

        var columns = m.Columns.AsArray();
        var settable = columns.Where(static c => !c.IsKey && !c.IsAutoGenerated).ToList();
        var keys = columns.Where(static c => c.IsKey).ToList();

        var sql = new StringBuilder();
        sql.Append("UPDATE ").Append(dialect.Quote(m.TableName)).Append(" SET ");
        for (var i = 0; i < settable.Count; i++)
        {
            if (i > 0)
            {
                sql.Append(", ");
            }
            sql.Append(dialect.Quote(settable[i].ColumnName)).Append(" = ").Append(Marker).Append(settable[i].PropertyName);
        }
        if (keys.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < keys.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                sql.Append(dialect.Quote(keys[i].ColumnName)).Append(" = ").Append(Marker).Append("k_").Append(keys[i].PropertyName);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var c in settable)
        {
            EmitColumnParameter(builder, Marker + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
        }
        foreach (var c in keys)
        {
            EmitColumnParameter(builder, Marker + "k_" + c.PropertyName, $"{m.EntityParamName}.{c.PropertyName}", c);
        }
    }

    private static void EmitDelete(SourceBuilder builder, DeleteModel m, SqlDialect dialect)
    {
        var keyColumns = m.Columns.AsArray().Where(static c => c.IsKey).ToList();
        var bindParams = BindParams(m);

        var sql = new StringBuilder();
        sql.Append("DELETE FROM ").Append(dialect.Quote(m.TableName));
        if (bindParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < bindParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = i < keyColumns.Count ? keyColumns[i].ColumnName : bindParams[i].ColumnName;
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(bindParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in bindParams)
        {
            EmitValueParamBinding(builder, p);
        }
    }

    private static void EmitSelect(SourceBuilder builder, SelectModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType)
        {
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(m.TableName));
            return;
        }

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(string.Join(", ", m.Columns.AsArray().Select(c => dialect.Quote(c.ColumnName)))).Append(" FROM ").Append(dialect.Quote(m.TableName));

        // Phase 7: append the provider paging clause when [Limit]/[Offset] params are present.
        var valueParams = m.ValueParams.AsArray();
        var limitParam = valueParams.FirstOrDefault(static p => p.IsLimit);
        var offsetParam = valueParams.FirstOrDefault(static p => p.IsOffset);
        if (limitParam is not null || offsetParam is not null)
        {
            dialect.AppendPaging(
                sql,
                limitParam is null ? null : Marker + limitParam.Name,
                offsetParam is null ? null : Marker + offsetParam.Name);
        }

        EmitCommandText(builder, sql.ToString());

        if (offsetParam is not null)
        {
            EmitValueParamBinding(builder, offsetParam);
        }
        if (limitParam is not null)
        {
            EmitValueParamBinding(builder, limitParam);
        }
    }

    private static void EmitSelectSingle(SourceBuilder builder, SelectSingleModel m, SqlDialect dialect)
    {
        if (!m.HasEntityType)
        {
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(m.TableName));
            return;
        }

        var keyColumns = m.Columns.AsArray().Where(static c => c.IsKey).ToList();
        var bindParams = BindParams(m);

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(string.Join(", ", m.Columns.AsArray().Select(c => dialect.Quote(c.ColumnName)))).Append(" FROM ").Append(dialect.Quote(m.TableName));
        if (bindParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < bindParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = i < keyColumns.Count ? keyColumns[i].ColumnName : bindParams[i].ColumnName;
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(bindParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in bindParams)
        {
            EmitValueParamBinding(builder, p);
        }
    }

    // Bind parameters = value parameters minus the [Limit]/[Offset] paging parameters.
    private static List<BuilderValueParam> BindParams(BuilderMethodModel m)
        => m.ValueParams.AsArray().Where(static p => !p.IsLimit && !p.IsOffset).ToList();

    // Entity column parameter: p.DbType from the resolved expression (explicit [DbType] or [TypeMap]);
    // p.Value via converter ToDb / enum underlying cast / null-coalesce (spec §7.4 / §7.7 / §7.9).
    private static void EmitColumnParameter(SourceBuilder builder, string paramName, string valueExpression, BuilderColumn c)
    {
        builder.Indent()
            .Append("{ var p = cmd.CreateParameter(); p.ParameterName = \"")
            .Append(paramName).Append("\"; ");

        if (c.DbTypeExpr is not null)
        {
            builder.Append("p.DbType = ").Append(c.DbTypeExpr).Append("; ");
            if (c.Size is { } sz)
            {
                builder.Append("p.Size = ").Append(sz.ToString(CultureInfo.InvariantCulture)).Append("; ");
            }
        }

        AppendColumnValue(builder, valueExpression, c);

        builder.Append(" cmd.Parameters.Add(p); }").NewLine();
    }

    private static void AppendColumnValue(SourceBuilder builder, string valueExpr, BuilderColumn c)
    {
        if (c.ConverterTypeFullName is not null)
        {
            if (c.IsNullableValueType)
            {
                builder.Append("p.Value = ")
                    .Append(valueExpr).Append(".HasValue ? (object)")
                    .Append(c.ConverterTypeFullName).Append(".ToDb(").Append(valueExpr).Append(".Value) : global::System.DBNull.Value;");
            }
            else if (c.IsValueType)
            {
                builder.Append("p.Value = (object)")
                    .Append(c.ConverterTypeFullName).Append(".ToDb(").Append(valueExpr).Append(");");
            }
            else
            {
                builder.Append("p.Value = ")
                    .Append(valueExpr).Append(" is null ? global::System.DBNull.Value : (object)")
                    .Append(c.ConverterTypeFullName).Append(".ToDb(").Append(valueExpr).Append(");");
            }
            return;
        }

        if (c.EnumUnderlyingFullName is not null)
        {
            AppendEnumValue(builder, valueExpr, c.EnumUnderlyingFullName, c.IsNullableEnum);
            return;
        }

        builder.Append("p.Value = (object?)").Append(valueExpr).Append(" ?? global::System.DBNull.Value;");
    }

    // Method value parameter: p.DbType from a [TypeMap] default; p.Value via enum underlying cast or
    // null-coalesce (method parameters do not resolve a converter — matching the prior behaviour).
    private static void EmitValueParamBinding(SourceBuilder builder, BuilderValueParam p)
    {
        builder.Indent()
            .Append("{ var p = cmd.CreateParameter(); p.ParameterName = \"")
            .Append(Marker).Append(p.Name).Append("\"; ");

        if (p.DbTypeExpr is not null)
        {
            builder.Append("p.DbType = ").Append(p.DbTypeExpr).Append("; ");
            if (p.Size is { } sz)
            {
                builder.Append("p.Size = ").Append(sz.ToString(CultureInfo.InvariantCulture)).Append("; ");
            }
        }

        if (p.EnumUnderlyingFullName is not null)
        {
            AppendEnumValue(builder, p.Name, p.EnumUnderlyingFullName, p.IsNullableEnum);
        }
        else
        {
            builder.Append("p.Value = (object?)").Append(p.Name).Append(" ?? global::System.DBNull.Value;");
        }

        builder.Append(" cmd.Parameters.Add(p); }").NewLine();
    }

    private static void AppendEnumValue(SourceBuilder builder, string valueExpr, string underlyingFq, bool isNullableEnum)
    {
        if (isNullableEnum)
        {
            builder.Append("p.Value = ").Append(valueExpr).Append(".HasValue ? (object)(")
                .Append(underlyingFq).Append(")").Append(valueExpr).Append(".Value : global::System.DBNull.Value;");
        }
        else
        {
            builder.Append("p.Value = (object)(").Append(underlyingFq).Append(")").Append(valueExpr).Append(";");
        }
    }

    private static void EmitCommandText(SourceBuilder builder, string sql)
        => builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sql)).Append(";").NewLine();

    private static string EncodeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
