namespace Smart.Data.Accessor.Builders.Generator.Engine;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using SourceGenerateHelper;

/// <summary>
/// Dialect-parameterized QueryBuilder emit engine. Each provider's <c>[Generator]</c> collects the
/// methods carrying its QueryBuilder-derived attributes and calls <see cref="Run"/> with its
/// <see cref="SqlDialect"/>. Shared source (linked into each builder generator assembly); the only
/// per-provider variation is identifier quoting + the paging clause (spec §4.3, Phase 7).
/// </summary>
internal static class QueryBuilderEngine
{
    private const string NameAttributeName = "Smart.Data.Accessor.Attributes.NameAttribute";
    private const string IgnoreAttributeName = "Smart.Data.Accessor.Attributes.IgnoreAttribute";
    private const string AutoGeneratedAttributeName = "Smart.Data.Accessor.Attributes.AutoGeneratedAttribute";
    private const string KeyAttributeName = "Smart.Data.Accessor.Attributes.KeyAttribute";
    private const string CancellationTokenTypeName = "System.Threading.CancellationToken";
    private const string LimitAttributeName = "Smart.Data.Accessor.Builders.LimitAttribute";
    private const string OffsetAttributeName = "Smart.Data.Accessor.Builders.OffsetAttribute";
    private const string QueryBuilderMethodSuffix = "__QueryBuilder";
    private const char Marker = '@';

    public enum BuilderKind
    {
        Insert,
        Update,
        Delete,
        Count,
        Select,
        SelectSingle,
        Truncate,
    }

    public static void Run(
        SourceProductionContext context,
        ImmutableArray<(GeneratorAttributeSyntaxContext Ctx, BuilderKind Kind)> entries,
        SqlDialect dialect)
    {
        var groups = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)>>(SymbolEqualityComparer.Default);
        var seenMethods = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);

        foreach (var (ctx, kind) in entries)
        {
            if (ctx.TargetSymbol is not IMethodSymbol method || ctx.TargetNode is not MethodDeclarationSyntax syntax)
            {
                continue;
            }

            var container = method.ContainingType;
            if (syntax.Parent is not ClassDeclarationSyntax containerSyntax || !containerSyntax.Modifiers.Any(t => t.Text == "partial"))
            {
                context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.InvalidContainer, syntax.Identifier.GetLocation(), container.Name));
                continue;
            }

            // SDB0006: more than one QueryBuilder attribute on the same method.
            if (!seenMethods.Add(method))
            {
                context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.QueryBuilderDuplicated, syntax.Identifier.GetLocation(), method.Name));
                continue;
            }

            // The attribute that matched this provider's metadata name for this entry.
            if (ctx.Attributes.Length == 0)
            {
                continue;
            }
            var attr = ctx.Attributes[0];

            if (!groups.TryGetValue(container, out var list))
            {
                list = [];
                groups[container] = list;
            }
            list.Add((method, attr, syntax, kind));
        }

        foreach (var kv in groups)
        {
            var source = Emit(context, kv.Key, kv.Value, dialect);
            var ns = kv.Key.ContainingNamespace.IsGlobalNamespace
                ? "global"
                : kv.Key.ContainingNamespace.ToDisplayString().Replace('.', '_');
            var filename = $"{ns}_{kv.Key.Name}.QueryBuilders.g.cs";
            context.AddSource(filename, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string Emit(SourceProductionContext context, INamedTypeSymbol container, List<(IMethodSymbol Method, AttributeData Attr, MethodDeclarationSyntax Syntax, BuilderKind Kind)> entries, SqlDialect dialect)
    {
        var builder = new SourceBuilder();
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.Indent().Append("#pragma warning disable").NewLine();
        builder.NewLine();

        var ns = container.ContainingNamespace.IsGlobalNamespace ? string.Empty : container.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        var typeMaps = MappingResolver.ReadTypeMaps(container);

        builder.Indent().Append(AccessibilityText(container.DeclaredAccessibility)).Append(" partial class ").Append(container.Name).NewLine();
        builder.BeginScope();

        var first = true;
        foreach (var (method, attr, syntax, kind) in entries)
        {
            if (!first)
            {
                builder.NewLine();
            }
            first = false;
            EmitMethod(context, builder, container, method, attr, syntax, kind, typeMaps, dialect);
        }

        builder.EndScope();
        return builder.ToString();
    }

    private static void EmitMethod(
        SourceProductionContext context,
        SourceBuilder builder,
        INamedTypeSymbol container,
        IMethodSymbol method,
        AttributeData attr,
        MethodDeclarationSyntax syntax,
        BuilderKind kind,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        var location = syntax.Identifier.GetLocation();

        // Resolve the metadata the derived attribute carries: EntityType (ctor arg) and Table (named arg).
        var entityType = attr.ConstructorArguments.Length > 0
            ? attr.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;
        string? table = null;
        foreach (var kv in attr.NamedArguments)
        {
            if (kv.Key == "Table" && kv.Value.Value is string s)
            {
                table = s;
            }
        }
        var tableName = table ?? entityType?.Name;
        if (tableName is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.MissingTable, location, method.Name));
            return;
        }

        // design doc §4.3: value parameters = method params excluding DbConnection / DbTransaction / CancellationToken.
        var valueParams = method.Parameters
            .Where(p => !IsCancellationToken(p.Type) && !IsDbConnection(p.Type) && !IsDbTransaction(p.Type))
            .ToList();

        // Phase 7: [Limit]/[Offset] params drive the dialect paging clause, not column/WHERE binding.
        var limitParam = valueParams.FirstOrDefault(p => HasAttribute(p, LimitAttributeName));
        var offsetParam = valueParams.FirstOrDefault(p => HasAttribute(p, OffsetAttributeName));
        var bindParams = valueParams.Where(p => !HasAttribute(p, LimitAttributeName) && !HasAttribute(p, OffsetAttributeName)).ToList();

        // Emit signature: private static void {Method}__QueryBuilder(ref BuilderContext ctx, <value params>)
        var sig = new StringBuilder();
        sig.Append("ref global::Smart.Data.Accessor.Builders.BuilderContext ctx");
        foreach (var p in valueParams)
        {
            sig.Append(", ").Append(p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(' ').Append(p.Name);
        }

        builder.Indent().Append("private static void ").Append(method.Name).Append(QueryBuilderMethodSuffix)
            .Append("(").Append(sig.ToString()).Append(")").NewLine();
        builder.BeginScope();
        builder.Indent().Append("var cmd = ctx.Command;").NewLine();

        // Entity instance: the first value parameter whose type matches the attribute's EntityType.
        var entityParam = entityType is null
            ? null
            : bindParams.FirstOrDefault(p => SymbolEqualityComparer.Default.Equals(p.Type, entityType));

        var columns = entityType is not null ? ReadEntityColumns(entityType) : null;

        switch (kind)
        {
            case BuilderKind.Insert:
                EmitInsert(context, builder, container, location, tableName, columns, entityParam, bindParams, typeMaps, dialect);
                break;
            case BuilderKind.Update:
                EmitUpdate(context, builder, container, method, location, entityType, tableName, columns, entityParam, typeMaps, dialect);
                break;
            case BuilderKind.Delete:
                EmitDelete(context, builder, method, location, entityType, tableName, columns, bindParams, typeMaps, dialect);
                break;
            case BuilderKind.Count:
                EmitCommandText(builder, "SELECT COUNT(*) FROM " + dialect.Quote(tableName));
                break;
            case BuilderKind.Truncate:
                EmitCommandText(builder, "TRUNCATE TABLE " + dialect.Quote(tableName));
                break;
            case BuilderKind.Select:
                EmitSelect(context, builder, location, method.Name, tableName, columns, limitParam, offsetParam, typeMaps, dialect);
                break;
            case BuilderKind.SelectSingle:
                EmitSelectSingle(context, builder, method, location, entityType, tableName, columns, bindParams, typeMaps, dialect);
                break;
        }

        builder.EndScope();
    }

    private static void EmitInsert(
        SourceProductionContext context,
        SourceBuilder builder,
        INamedTypeSymbol container,
        Location location,
        string tableName,
        List<EntityColumn>? columns,
        IParameterSymbol? entityParam,
        List<IParameterSymbol> valueParams,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        if (columns is not null && entityParam is not null)
        {
            // Entity mode: columns from entity properties (excluding [Ignore] / [AutoGenerated]).
            var cols = columns.Where(c => !c.IsAutoGenerated).ToList();
            var colSql = string.Join(", ", cols.Select(c => dialect.Quote(c.Column)));
            var valSql = string.Join(", ", cols.Select(c => Marker + c.PropertyName));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(tableName)} ({colSql}) VALUES ({valSql})");
            foreach (var c in cols)
            {
                ParameterEmitter.EmitEntityPropertyParameter(
                    builder, Marker + c.PropertyName, $"{entityParam.Name}.{c.PropertyName}", c.Symbol, typeMaps, container, context, location);
            }
        }
        else
        {
            // Parameter mode: columns / values from the method's value parameters.
            var colSql = string.Join(", ", valueParams.Select(p => dialect.Quote(ColumnName(p))));
            var valSql = string.Join(", ", valueParams.Select(p => Marker + p.Name));
            EmitCommandText(builder, $"INSERT INTO {dialect.Quote(tableName)} ({colSql}) VALUES ({valSql})");
            foreach (var p in valueParams)
            {
                ParameterEmitter.EmitMethodParameterBinding(builder, Marker + p.Name, p.Name, p.Type, typeMaps);
            }
        }
    }

    private static void EmitUpdate(
        SourceProductionContext context,
        SourceBuilder builder,
        INamedTypeSymbol container,
        IMethodSymbol method,
        Location location,
        INamedTypeSymbol? entityType,
        string tableName,
        List<EntityColumn>? columns,
        IParameterSymbol? entityParam,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        if (columns is null || entityParam is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, method.Name));
            EmitCommandText(builder, "UPDATE " + dialect.Quote(tableName) + " SET ");
            return;
        }

        var settable = columns.Where(c => !c.IsKey && !c.IsAutoGenerated).ToList();
        var keys = columns.Where(c => c.IsKey).ToList();
        if (keys.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType!.Name, method.Name));
        }

        var sql = new StringBuilder();
        sql.Append("UPDATE ").Append(dialect.Quote(tableName)).Append(" SET ");
        for (var i = 0; i < settable.Count; i++)
        {
            if (i > 0)
            {
                sql.Append(", ");
            }
            sql.Append(dialect.Quote(settable[i].Column)).Append(" = ").Append(Marker).Append(settable[i].PropertyName);
        }
        if (keys.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < keys.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                sql.Append(dialect.Quote(keys[i].Column)).Append(" = ").Append(Marker).Append("k_").Append(keys[i].PropertyName);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var c in settable)
        {
            ParameterEmitter.EmitEntityPropertyParameter(
                builder, Marker + c.PropertyName, $"{entityParam.Name}.{c.PropertyName}", c.Symbol, typeMaps, container, context, location);
        }
        foreach (var c in keys)
        {
            ParameterEmitter.EmitEntityPropertyParameter(
                builder, Marker + "k_" + c.PropertyName, $"{entityParam.Name}.{c.PropertyName}", c.Symbol, typeMaps, container, context, location);
        }
    }

    private static void EmitDelete(
        SourceProductionContext context,
        SourceBuilder builder,
        IMethodSymbol method,
        Location location,
        INamedTypeSymbol? entityType,
        string tableName,
        List<EntityColumn>? columns,
        List<IParameterSymbol> valueParams,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        var keyColumns = columns?.Where(c => c.IsKey).ToList();
        if (entityType is not null && (keyColumns is null || keyColumns.Count == 0))
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType.Name, method.Name));
        }

        var sql = new StringBuilder();
        sql.Append("DELETE FROM ").Append(dialect.Quote(tableName));
        if (valueParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < valueParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = keyColumns is not null && i < keyColumns.Count ? keyColumns[i].Column : ColumnName(valueParams[i]);
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(valueParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in valueParams)
        {
            ParameterEmitter.EmitMethodParameterBinding(builder, Marker + p.Name, p.Name, p.Type, typeMaps);
        }
    }

    private static void EmitSelect(
        SourceProductionContext context,
        SourceBuilder builder,
        Location location,
        string methodName,
        string tableName,
        List<EntityColumn>? columns,
        IParameterSymbol? limitParam,
        IParameterSymbol? offsetParam,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        if (columns is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, methodName));
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(tableName));
            return;
        }

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(string.Join(", ", columns.Select(c => dialect.Quote(c.Column)))).Append(" FROM ").Append(dialect.Quote(tableName));

        // Phase 7: append the provider paging clause when [Limit]/[Offset] params are present.
        if (limitParam is not null || offsetParam is not null)
        {
            dialect.AppendPaging(
                sql,
                limitParam is null ? null : Marker + limitParam.Name,
                offsetParam is null ? null : Marker + offsetParam.Name);
        }

        EmitCommandText(builder, sql.ToString());

        if (offsetParam is not null)
        {
            ParameterEmitter.EmitMethodParameterBinding(builder, Marker + offsetParam.Name, offsetParam.Name, offsetParam.Type, typeMaps);
        }
        if (limitParam is not null)
        {
            ParameterEmitter.EmitMethodParameterBinding(builder, Marker + limitParam.Name, limitParam.Name, limitParam.Type, typeMaps);
        }
    }

    private static void EmitSelectSingle(
        SourceProductionContext context,
        SourceBuilder builder,
        IMethodSymbol method,
        Location location,
        INamedTypeSymbol? entityType,
        string tableName,
        List<EntityColumn>? columns,
        List<IParameterSymbol> valueParams,
        Dictionary<ITypeSymbol, TypeMapInfo> typeMaps,
        SqlDialect dialect)
    {
        if (columns is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.SelectColumnsUnresolvable, location, method.Name));
            EmitCommandText(builder, "SELECT * FROM " + dialect.Quote(tableName));
            return;
        }

        var keyColumns = columns.Where(c => c.IsKey).ToList();
        if (entityType is not null && keyColumns.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(BuilderDiagnostics.NoKeyForBuilder, location, entityType.Name, method.Name));
        }

        var sql = new StringBuilder();
        sql.Append("SELECT ").Append(string.Join(", ", columns.Select(c => dialect.Quote(c.Column)))).Append(" FROM ").Append(dialect.Quote(tableName));
        if (valueParams.Count > 0)
        {
            sql.Append(" WHERE ");
            for (var i = 0; i < valueParams.Count; i++)
            {
                if (i > 0)
                {
                    sql.Append(" AND ");
                }
                var column = i < keyColumns.Count ? keyColumns[i].Column : ColumnName(valueParams[i]);
                sql.Append(dialect.Quote(column)).Append(" = ").Append(Marker).Append(valueParams[i].Name);
            }
        }

        EmitCommandText(builder, sql.ToString());

        foreach (var p in valueParams)
        {
            ParameterEmitter.EmitMethodParameterBinding(builder, Marker + p.Name, p.Name, p.Type, typeMaps);
        }
    }

    private static void EmitCommandText(SourceBuilder builder, string sql)
        => builder.Indent().Append("cmd.CommandText = ").Append(EncodeStringLiteral(sql)).Append(";").NewLine();

    private static List<EntityColumn> ReadEntityColumns(INamedTypeSymbol entityType)
    {
        var list = new List<EntityColumn>();
        foreach (var p in entityType.GetMembers().OfType<IPropertySymbol>())
        {
            if (p.DeclaredAccessibility != Accessibility.Public || p.IsStatic || p.GetMethod is null)
            {
                continue;
            }
            if (p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == IgnoreAttributeName))
            {
                continue;
            }
            var column = p.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
                ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;
            var isKey = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == KeyAttributeName);
            var isAuto = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AutoGeneratedAttributeName);
            list.Add(new EntityColumn(column, p.Name, isKey, isAuto, p));
        }
        return list;
    }

    private static string ColumnName(IParameterSymbol p)
        => p.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == NameAttributeName)
            ?.ConstructorArguments.FirstOrDefault().Value as string ?? p.Name;

    private static bool HasAttribute(IParameterSymbol p, string attributeName)
        => p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attributeName);

    private static bool IsCancellationToken(ITypeSymbol type) => type.ToDisplayString() == CancellationTokenTypeName;

    private static bool IsDbConnection(ITypeSymbol type) => InheritsFrom(type, "System.Data.Common.DbConnection");

    private static bool IsDbTransaction(ITypeSymbol type) => InheritsFrom(type, "System.Data.Common.DbTransaction");

    private static bool InheritsFrom(ITypeSymbol type, string baseFullName)
    {
        for (var current = type as INamedTypeSymbol; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == baseFullName)
            {
                return true;
            }
        }
        return false;
    }

    private static string EncodeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(ch); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string AccessibilityText(Accessibility a) => a switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal",
    };

    private readonly record struct EntityColumn(string Column, string PropertyName, bool IsKey, bool IsAutoGenerated, IPropertySymbol Symbol);
}
